
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Mar 21 12:31:33 CET 2024
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 33;
  public static final int SHOW = 46;
  public static final int DISTINTO = 16;
  public static final int CONST = 50;
  public static final int LLCIERRE = 26;
  public static final int POR = 7;
  public static final int CCIERRE = 24;
  public static final int PUNTOYCOMA = 30;
  public static final int PCIERRE = 22;
  public static final int CASE = 42;
  public static final int CAP = 23;
  public static final int REPEAT = 36;
  public static final int FOR = 35;
  public static final int NOT = 20;
  public static final int MENORIGUAL = 15;
  public static final int AND = 18;
  public static final int IGUAL = 28;
  public static final int LLAP = 25;
  public static final int IGUALDAD = 17;
  public static final int OR = 19;
  public static final int PRODLIST = 11;
  public static final int DIV = 8;
  public static final int VALUEFOR = 41;
  public static final int TYPEDEF = 49;
  public static final int MAIN = 48;
  public static final int IF = 37;
  public static final int AMPERSAND = 31;
  public static final int MAYORIGUAL = 14;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int TRUE = 55;
  public static final int NEW = 52;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int MENOS = 6;
  public static final int MENOR = 13;
  public static final int MOD = 9;
  public static final int BREAK = 43;
  public static final int VOID = 4;
  public static final int TIPOINT = 2;
  public static final int SWITCH = 40;
  public static final int MAYOR = 12;
  public static final int ENT = 54;
  public static final int PAP = 21;
  public static final int FLECHA = 27;
  public static final int ELSE = 38;
  public static final int PUNTO = 32;
  public static final int READ = 47;
  public static final int IDEN = 53;
  public static final int WHILE = 34;
  public static final int LIST = 51;
  public static final int SUMLIST = 10;
  public static final int DEFAULT = 44;
  public static final int TIPOBOOL = 3;
  public static final int FALSE = 56;
  public static final int STRUCT = 39;
  public static final int MAS = 5;
}

