
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Mar 05 18:28:19 CET 2024
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 42;
  public static final int SHOW = 56;
  public static final int DISTINTO = 21;
  public static final int LLCIERRE = 31;
  public static final int POR = 11;
  public static final int PUNTOYCOMA = 37;
  public static final int CCIERRE = 29;
  public static final int CONCAT = 16;
  public static final int PCIERRE = 27;
  public static final int CASE = 52;
  public static final int CAP = 28;
  public static final int REPEAT = 46;
  public static final int FOR = 45;
  public static final int MENORIGUAL = 20;
  public static final int AND = 23;
  public static final int IGUAL = 35;
  public static final int LLAP = 30;
  public static final int IGUALDAD = 22;
  public static final int OR = 24;
  public static final int ARROBA = 43;
  public static final int PRODLIST = 15;
  public static final int DIV = 12;
  public static final int VALUEFOR = 51;
  public static final int TYPEDEF = 59;
  public static final int MAIN = 58;
  public static final int IF = 47;
  public static final int COMILLASDOBLES = 40;
  public static final int AMPERSAND = 38;
  public static final int MAYORIGUAL = 19;
  public static final int EOF = 0;
  public static final int RETURN = 55;
  public static final int TRUE = 7;
  public static final int error = 1;
  public static final int COMA = 36;
  public static final int NEGACION = 25;
  public static final int MENOS = 10;
  public static final int MENOR = 18;
  public static final int MOD = 13;
  public static final int BREAK = 53;
  public static final int VOID = 5;
  public static final int TIPOINT = 3;
  public static final int SWITCH = 50;
  public static final int MAYOR = 17;
  public static final int ENT = 6;
  public static final int PUNTOS = 34;
  public static final int PAP = 26;
  public static final int BARRA = 33;
  public static final int FLECHA = 32;
  public static final int ELSE = 48;
  public static final int PUNTO = 41;
  public static final int READ = 57;
  public static final int IDEN = 2;
  public static final int WHILE = 44;
  public static final int SUMLIST = 14;
  public static final int DEFAULT = 54;
  public static final int TIPOBOOL = 4;
  public static final int FALSE = 8;
  public static final int STRUCT = 49;
  public static final int ALMOHADILLA = 39;
  public static final int MAS = 9;
}

