
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Mar 20 18:32:29 CET 2024
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 37;
  public static final int SHOW = 50;
  public static final int DISTINTO = 20;
  public static final int CONST = 54;
  public static final int LLCIERRE = 30;
  public static final int POR = 11;
  public static final int CCIERRE = 28;
  public static final int PUNTOYCOMA = 34;
  public static final int PCIERRE = 26;
  public static final int CASE = 46;
  public static final int CAP = 27;
  public static final int REPEAT = 40;
  public static final int FOR = 39;
  public static final int NOT = 24;
  public static final int MENORIGUAL = 19;
  public static final int AND = 22;
  public static final int IGUAL = 32;
  public static final int LLAP = 29;
  public static final int IGUALDAD = 21;
  public static final int OR = 23;
  public static final int PRODLIST = 15;
  public static final int DIV = 12;
  public static final int VALUEFOR = 45;
  public static final int TYPEDEF = 53;
  public static final int MAIN = 52;
  public static final int IF = 41;
  public static final int AMPERSAND = 35;
  public static final int MAYORIGUAL = 18;
  public static final int EOF = 0;
  public static final int RETURN = 49;
  public static final int TRUE = 7;
  public static final int NEW = 56;
  public static final int error = 1;
  public static final int COMA = 33;
  public static final int MENOS = 10;
  public static final int MENOR = 17;
  public static final int MOD = 13;
  public static final int BREAK = 47;
  public static final int VOID = 5;
  public static final int TIPOINT = 3;
  public static final int SWITCH = 44;
  public static final int MAYOR = 16;
  public static final int ENT = 6;
  public static final int PAP = 25;
  public static final int FLECHA = 31;
  public static final int ELSE = 42;
  public static final int PUNTO = 36;
  public static final int READ = 51;
  public static final int IDEN = 2;
  public static final int WHILE = 38;
  public static final int LIST = 55;
  public static final int SUMLIST = 14;
  public static final int DEFAULT = 48;
  public static final int TIPOBOOL = 4;
  public static final int FALSE = 8;
  public static final int STRUCT = 43;
  public static final int MAS = 9;
}

